name: prisma_schema
description: A starting point for Dart libraries or applications.
version: 0.0.1
environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  freezed_annotation: ^2.2.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  build_runner: ^2.3.3
  freezed: ^2.3.2
  import_sorter: ^4.6.0

import_sorter:
  emojis: true
